### PR TITLE
Update icu pin

### PR DESCRIPTION
**Pull request by ocefpaf**
cc @mingwandroid

### CODE REVIEW

**Comment by ocefpaf** [comment]
@gillins any idea what is going on with Windows in PY27+ARCH64?

```
opyright (C) Microsoft Corporation 2005. All rights reserved.
projects\Win32\VC9\xerces-all\xerces-all.sln(1): Solution file error MSB5014: File format version is not recognized.  MSBuild can only read solution files between versions 7.0 and 9.0, inclusive.
```

**Comment by gillins** [comment]
@ocefpaf something changed on AppVeyor I think. I've sent you a PR - let me know if that fixes it or not.

**Comment by ocefpaf** [comment]
> @ocefpaf something changed on AppVeyor I think. I've sent you a PR - let me know if that fixes it or not.

:tada: worked like a charm.

**Comment by ocefpaf** [comment]
From build https://travis-ci.org/conda-forge/xerces-c-feedstock/builds/197360429 we know that Travis-CI is passing. Merging this and monitoring the `OS X` on `master`.

**Pull request merged**
