### PR TITLE
Restore building/configuring for the Socket NetAccessor

### PR DESCRIPTION
**Pull request by wsfulton**
The default NetAccessor was changed upstream in xerces-c 3.2.4 to the Curl NetAccessor. Go back to using the Socket Accessor as it works. The Curl NetAccessor is fundamentally broken see https://issues.apache.org/jira/browse/XERCESC-2250.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by wsfulton** [comment]
@conda-forge-admin, please rerender

**Comment by wsfulton** [comment]
I think the combined changes in #33 and #35 ought to have been along the lines in this merge request instead.

**Comment by gillins** [comment]
Is this likely to break anyone's code? Do we need to have a migration?

**Comment by wsfulton** [comment]
The Curl NetAccessor is quite broken for anything other than the smallest of xml files. So while some users may not notice it is broken, I don't think there is any serious use of the NetAccessor by conda-forge users, otherwise this problem would have been reported before. NetAccessors were not being used at all until I enabled it in #18. I think this patch is just restoring it to how it used to be in 3.2.3.

While both the Socket and Curl NetAccessors provide network access to xml files, they are clearly different implementations and offer different protocols. The only thing I can think that might break is if someone is using https on a small file, a switch back to the socket NetAccessor will break as https is not provided by the Socket NetAccessor. So the way I see it is until 3.3.0 is released we have a choice of:

1. Flaky/non-functional Curl NetAccessor with https support.
2. Robust Socket implementation without https support.

As an alternative to this patch, would it be possible to provide two builds of 3.2.x - one with the Socket NetAccessor and one with the Curl NetAccessor. This segue ways into another related topic I wanted to bring up at some point. How can we have different packages with different options passed to configure. For example, a build for static linking instead of dynamic linking.

I don't understand what is required for 'a migration', could you elaborate?

**Comment by gillins** [comment]
Sorry, I should have been more specific. Will this PR remove already exported functions that downstream packages may be using? Or rename functions?
Doing either of the above will mean we'll have to recompile everything using this package (migration) to be sure there is no breakage.

> This segue ways into another related topic I wanted to bring up at some point. How can we have different packages with different options passed to configure.

@ocefpaf may know more about this...

**Comment by wsfulton** [comment]
Perhaps putting my neck on the line when it would be safer to say yes, but I don't think a migration is needed.

The reason is the NetAccessors are an implementation detail within xerces. More specifically, the NetAccessor headers  `xercesc/util/NetAccessors/Curl/*.hpp` which are removed and replaced by `xercesc/util/NetAccessors/Socket/*.hpp` are not included in any other xerces headers. It is possible that users could include the NetAccessor headers directly, but I can't think of a reason to do that and so is highly unlikely. Of course it would be safer to rebuild downstream packages, but it is probably unwarranted. 

No functions have been renamed.

**Comment by ocefpaf** [comment]
I'm not an expert to say it will or will not break things. With that said. I'm OK testing this out but we may remove/mark as broken if something goes awry.

**Pull request merged**
